=== jack4M/XTBCNB/cnb/utf8/vydani.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- $Revision:   1.1  $ -->
<!ELEMENT VYDANI (IDENTIFIKACE-ZPRAVY, ADRESA*, IDENTIFIKACE-VYKAZU, DATA?, POZNAMKA?)>
<!ELEMENT IDENTIFIKACE-ZPRAVY (ZASLAL, CISLO-ZPRAVY, CASTECNA-ZPRAVA?, NAZEV-DOKUMENTU, METODIKA, FUNKCE-ZPRAVY, DATUM)>
<!ELEMENT ZASLAL (#PCDATA)>
<!ELEMENT CISLO-ZPRAVY (#PCDATA)>
<!ELEMENT CASTECNA-ZPRAVA (CISLO-VYDANI)>
<!ATTLIST CASTECNA-ZPRAVA PORADI CDATA #REQUIRED>
<!ATTLIST CASTECNA-ZPRAVA TYP (První | Poslední) #IMPLIED>
<!ELEMENT CISLO-VYDANI (#PCDATA)>
<!ELEMENT NAZEV-DOKUMENTU EMPTY>
<!ATTLIST NAZEV-DOKUMENTU
	KOD (Vydání-výskytu-výkazu) #REQUIRED
>
<!ELEMENT METODIKA (#PCDATA)>
<!ELEMENT FUNKCE-ZPRAVY EMPTY>
<!ATTLIST FUNKCE-ZPRAVY
	KOD (Ostrá | Testovací) #REQUIRED
>
<!ELEMENT DATUM (#PCDATA)>
<!ELEMENT ADRESA (KOD-SUBJEKTU?, NAZEV-SUBJEKTU?, MESTO?, PSC?, ULICE?, KONTAKT*)>
<!ATTLIST ADRESA
	STRANA (Příjemce | Odesílatel | Centrální-banka | Zástupce-příjemce | Zástupce-odesílatele) #REQUIRED
>
<!ELEMENT KOD-SUBJEKTU (#PCDATA)>
<!ELEMENT NAZEV-SUBJEKTU (#PCDATA)>
<!ELEMENT MESTO (#PCDATA)>
<!ELEMENT PSC (#PCDATA)>
<!ELEMENT ULICE (#PCDATA)>
<!ELEMENT KONTAKT (KOD-ODDELENI?, JMENO-OSOBY?, SPOJENI*)>
<!ATTLIST KONTAKT
	KOD-FUNKCE (Informační-kontakt | Vedoucí-provozu | Pracovník-provozu | Celková-odpovědnost | Osoba-odpovědná-za-obsah) "Informační-kontakt"
>
<!ELEMENT KOD-ODDELENI (#PCDATA)>
<!ELEMENT JMENO-OSOBY (#PCDATA)>
<!ELEMENT SPOJENI (#PCDATA)>
<!ATTLIST SPOJENI
	TYP (Telefon | Fax | Email | EDI | Telex) #REQUIRED
>
<!ELEMENT IDENTIFIKACE-VYKAZU (DATOVY-SOUBOR, VYSKYT, STATUS, DUVOD, REFERENCNI-ZPRAVA?, AUDIT?)>
<!ELEMENT DATOVY-SOUBOR (#PCDATA)>
<!ELEMENT VYSKYT (SUBJEKT, ROZSAH-SUBJEKTU, STAV-KE-DNI)>
<!ELEMENT SUBJEKT (#PCDATA)>
<!ELEMENT ROZSAH-SUBJEKTU (#PCDATA)>
<!ELEMENT STAV-KE-DNI (#PCDATA)>
<!ELEMENT STATUS EMPTY>
<!ATTLIST STATUS
	KOD (Nová-data | Oprava | Storno | Potvrzení | Dotaz| Změnová-oprava | Storno-DZ) #REQUIRED
>
<!ELEMENT DUVOD EMPTY>
<!ATTLIST DUVOD
	KOD (Na-základě-metodiky | Na-základě-požadavku-centrální-banky | Úmysl-vykazujícího-subjektu) #REQUIRED
>
<!ELEMENT REFERENCNI-ZPRAVA (#PCDATA)>
<!ELEMENT AUDIT EMPTY>
<!ATTLIST AUDIT
	KOD (Data-před-auditem | Data-po-auditu) #REQUIRED
>
<!ELEMENT DATA (DATOVA-OBLAST+ | BLOK+ )>
<!ATTLIST DATOVA-OBLAST
	KOD CDATA #REQUIRED
>
<!ELEMENT DATOVA-OBLAST (RADEK*)>
<!ELEMENT RADEK (SLOUPEC*)>
<!ATTLIST RADEK
	PORADI CDATA #REQUIRED
>
<!ELEMENT SLOUPEC (#PCDATA)>
<!ATTLIST SLOUPEC
	PORADI CDATA #REQUIRED
>
<!ELEMENT BLOK (#PCDATA)>
<!ELEMENT POZNAMKA (#PCDATA)>

=== jack4M/XTBCNB/cnb/utf8/MOKAS42_28022013_717443.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE VYDANI SYSTEM "vydani.dtd">
<VYDANI>
	<IDENTIFIKACE-ZPRAVY>
		<ZASLAL>27867102</ZASLAL>
		<CISLO-ZPRAVY>717443</CISLO-ZPRAVY>
		<NAZEV-DOKUMENTU KOD="Vydání-výskytu-výkazu"></NAZEV-DOKUMENTU>
		<METODIKA>MKT20130101.01</METODIKA>
		<FUNKCE-ZPRAVY KOD="Testovací"></FUNKCE-ZPRAVY>
		<DATUM>20130509</DATUM>
	</IDENTIFIKACE-ZPRAVY>
	<ADRESA STRANA="Odesílatel">
		<KOD-SUBJEKTU>27867102</KOD-SUBJEKTU>
		<NAZEV-SUBJEKTU>X-TRADE BROKERS DOM MAKLERSKI SPóŁKA AKCYJNA, organizační složka</NAZEV-SUBJEKTU>
		<MESTO>Praha 8</MESTO>
		<PSC>180 00</PSC>
		<ULICE>Pobřežní 12</ULICE>
		<KONTAKT KOD-FUNKCE="Osoba-odpovědná-za-obsah">
			<JMENO-OSOBY>Tomáš Drábek</JMENO-OSOBY>
			<SPOJENI TYP="Telefon">226 259 930-930</SPOJENI>
			<SPOJENI TYP="Fax">226259903-903</SPOJENI>
		</KONTAKT>
	</ADRESA>
	<IDENTIFIKACE-VYKAZU>
		<DATOVY-SOUBOR>MOKAS42.04.00</DATOVY-SOUBOR>
		<VYSKYT>
			<SUBJEKT>27867102</SUBJEKT>
			<ROZSAH-SUBJEKTU>S_BCPZB</ROZSAH-SUBJEKTU>
			<STAV-KE-DNI>20130228</STAV-KE-DNI>
		</VYSKYT>
		<STATUS KOD="Nová-data"></STATUS>
		<DUVOD KOD="Na-základě-metodiky"></DUVOD>
		<AUDIT KOD="Data-před-auditem"></AUDIT>
	</IDENTIFIKACE-VYKAZU>
	<DATA>
		<DATOVA-OBLAST KOD="MOKA42_11">
			<RADEK PORADI="1">
				<SLOUPEC PORADI="1">x</SLOUPEC>
				<SLOUPEC PORADI="2">AED</SLOUPEC>
				<SLOUPEC PORADI="3">02</SLOUPEC>
				<SLOUPEC PORADI="4">x</SLOUPEC>
				<SLOUPEC PORADI="5">x</SLOUPEC>
				<SLOUPEC PORADI="6">x</SLOUPEC>
				<SLOUPEC PORADI="7">x</SLOUPEC>
				<SLOUPEC PORADI="8">x</SLOUPEC>
				<SLOUPEC PORADI="9">x</SLOUPEC>
				<SLOUPEC PORADI="10">x</SLOUPEC>
				<SLOUPEC PORADI="11">x</SLOUPEC>
				<SLOUPEC PORADI="12">x</SLOUPEC>
				<SLOUPEC PORADI="13">x</SLOUPEC>
				<SLOUPEC PORADI="14">x</SLOUPEC>
				<SLOUPEC PORADI="15">x</SLOUPEC>
				<SLOUPEC PORADI="16">x</SLOUPEC>
				<SLOUPEC PORADI="17">x</SLOUPEC>
				<SLOUPEC PORADI="18">x</SLOUPEC>
				<SLOUPEC PORADI="19">x</SLOUPEC>
				<SLOUPEC PORADI="20">x</SLOUPEC>
				<SLOUPEC PORADI="21">x</SLOUPEC>
				<SLOUPEC PORADI="22">x</SLOUPEC>
				<SLOUPEC PORADI="23">x</SLOUPEC>
				<SLOUPEC PORADI="24">x</SLOUPEC>
				<SLOUPEC PORADI="25">x</SLOUPEC>
				<SLOUPEC PORADI="26">x</SLOUPEC>
				<SLOUPEC PORADI="27">x</SLOUPEC>
				<SLOUPEC PORADI="28">x</SLOUPEC>
				<SLOUPEC PORADI="29">x</SLOUPEC>
				<SLOUPEC PORADI="30">x</SLOUPEC>
			</RADEK>
		</DATOVA-OBLAST>
	</DATA>
</VYDANI>

=== jack4M/XTBCNB/cnb/win1250/MOKAS41_28022013_717440.xml
<?xml version="1.0" encoding="windows-1250"?>
<!DOCTYPE VYDANI SYSTEM "vydani.dtd">
<VYDANI>
	<IDENTIFIKACE-ZPRAVY>
		<ZASLAL>27867102</ZASLAL>
		<CISLO-ZPRAVY>717440</CISLO-ZPRAVY>
		<NAZEV-DOKUMENTU KOD="Vydání-výskytu-výkazu"></NAZEV-DOKUMENTU>
		<METODIKA>MKT20130101.01</METODIKA>
		<FUNKCE-ZPRAVY KOD="Testovací"></FUNKCE-ZPRAVY>
		<DATUM>20130510</DATUM>
	</IDENTIFIKACE-ZPRAVY>
	<ADRESA STRANA="Odesílatel">
		<KOD-SUBJEKTU>27867102</KOD-SUBJEKTU>
		<NAZEV-SUBJEKTU>X-TRADE BROKERS DOM MAKLERSKI SPó£KA AKCYJNA, organizaèní složka</NAZEV-SUBJEKTU>
		<MESTO>Praha 8</MESTO>
		<PSC>180 00</PSC>
		<ULICE>Pobøežní 12</ULICE>
		<KONTAKT KOD-FUNKCE="Osoba-odpovìdná-za-obsah">
			<JMENO-OSOBY>Tomáš Drábek</JMENO-OSOBY>
			<SPOJENI TYP="Telefon">226 259 930-930</SPOJENI>
			<SPOJENI TYP="Fax">226259903-903</SPOJENI>
		</KONTAKT>
	</ADRESA>
	<IDENTIFIKACE-VYKAZU>
		<DATOVY-SOUBOR>MOKAS41.04.00</DATOVY-SOUBOR>
		<VYSKYT>
			<SUBJEKT>27867102</SUBJEKT>
			<ROZSAH-SUBJEKTU>S_BCPZB</ROZSAH-SUBJEKTU>
			<STAV-KE-DNI>20130228</STAV-KE-DNI>
		</VYSKYT>
		<STATUS KOD="Nová-data"></STATUS>
		<DUVOD KOD="Na-základì-metodiky"></DUVOD>
		<AUDIT KOD="Data-pøed-auditem"></AUDIT>
	</IDENTIFIKACE-VYKAZU>
	<DATA>
		<DATOVA-OBLAST KOD="MOKA41_11">
			<RADEK PORADI="1">
				<SLOUPEC PORADI="1">x</SLOUPEC>
				<SLOUPEC PORADI="2">AED</SLOUPEC>
				<SLOUPEC PORADI="3">04</SLOUPEC>
				<SLOUPEC PORADI="4">02</SLOUPEC>
				<SLOUPEC PORADI="5">x</SLOUPEC>
				<SLOUPEC PORADI="6">x</SLOUPEC>
				<SLOUPEC PORADI="7">x</SLOUPEC>
				<SLOUPEC PORADI="8">x</SLOUPEC>
				<SLOUPEC PORADI="9">x</SLOUPEC>
				<SLOUPEC PORADI="10">x</SLOUPEC>
				<SLOUPEC PORADI="11">x</SLOUPEC>
				<SLOUPEC PORADI="12">x</SLOUPEC>
				<SLOUPEC PORADI="13">x</SLOUPEC>
				<SLOUPEC PORADI="14">x</SLOUPEC>
				<SLOUPEC PORADI="15">x</SLOUPEC>
				<SLOUPEC PORADI="16">x</SLOUPEC>
				<SLOUPEC PORADI="17">x</SLOUPEC>
				<SLOUPEC PORADI="18">x</SLOUPEC>
				<SLOUPEC PORADI="19">x</SLOUPEC>
				<SLOUPEC PORADI="20">x</SLOUPEC>
				<SLOUPEC PORADI="21">x</SLOUPEC>
				<SLOUPEC PORADI="22">x</SLOUPEC>
				<SLOUPEC PORADI="23">x</SLOUPEC>
				<SLOUPEC PORADI="24">x</SLOUPEC>
				<SLOUPEC PORADI="25">x</SLOUPEC>
				<SLOUPEC PORADI="26">x</SLOUPEC>
				<SLOUPEC PORADI="27">x</SLOUPEC>
				<SLOUPEC PORADI="28">x</SLOUPEC>
				<SLOUPEC PORADI="29">x</SLOUPEC>
				<SLOUPEC PORADI="30">x</SLOUPEC>
				<SLOUPEC PORADI="31">x</SLOUPEC>
				<SLOUPEC PORADI="32">x</SLOUPEC>
				<SLOUPEC PORADI="33">x</SLOUPEC>
				<SLOUPEC PORADI="34">x</SLOUPEC>
				<SLOUPEC PORADI="35">x</SLOUPEC>
				<SLOUPEC PORADI="36">x</SLOUPEC>
				<SLOUPEC PORADI="37">x</SLOUPEC>
				<SLOUPEC PORADI="38">x</SLOUPEC>
				<SLOUPEC PORADI="39">x</SLOUPEC>
				<SLOUPEC PORADI="40">x</SLOUPEC>
			</RADEK>
		</DATOVA-OBLAST>
	</DATA>
</VYDANI>

=== jack4M/XTBCNB/cnb/2014-01/41-short.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE VYDANI SYSTEM "vydani.dtd">
<VYDANI>
	<IDENTIFIKACE-ZPRAVY>
		<ZASLAL>27867102</ZASLAL>
		<CISLO-ZPRAVY>795781</CISLO-ZPRAVY>
		<NAZEV-DOKUMENTU KOD="Vydání-výskytu-výkazu"></NAZEV-DOKUMENTU>
		<METODIKA>MKT20130101.01</METODIKA>
		<FUNKCE-ZPRAVY KOD="Testovací"></FUNKCE-ZPRAVY>
		<DATUM>20140107</DATUM>
	</IDENTIFIKACE-ZPRAVY>
	<ADRESA STRANA="Odesílatel">
		<KOD-SUBJEKTU>27867102</KOD-SUBJEKTU>
		<NAZEV-SUBJEKTU>X-TRADE BROKERS DOM MAKLERSKI SPóŁKA AKCYJNA, organizační složka</NAZEV-SUBJEKTU>
		<MESTO>Praha 8</MESTO>
		<PSC>180 00</PSC>
		<ULICE>Pobřežní 12</ULICE>
		<KONTAKT KOD-FUNKCE="Osoba-odpovědná-za-obsah">
			<JMENO-OSOBY>Tomáš Drábek</JMENO-OSOBY>
			<SPOJENI TYP="Telefon">226 259 930-930</SPOJENI>
			<SPOJENI TYP="Fax">226259903-903</SPOJENI>
		</KONTAKT>
	</ADRESA>
	<IDENTIFIKACE-VYKAZU>
		<DATOVY-SOUBOR>MOKAS41.04.00</DATOVY-SOUBOR>
		<VYSKYT>
			<SUBJEKT>27867102</SUBJEKT>
			<ROZSAH-SUBJEKTU>S_BCPZB</ROZSAH-SUBJEKTU>
			<STAV-KE-DNI>20130831</STAV-KE-DNI>
		</VYSKYT>
		<STATUS KOD="Nová-data"></STATUS>
		<DUVOD KOD="Na-základě-metodiky"></DUVOD>
		<AUDIT KOD="Data-před-auditem"></AUDIT>
	</IDENTIFIKACE-VYKAZU>
	<DATA>
		<DATOVA-OBLAST KOD="MOKA41_11">
<RADEK PORADI="1">																	
	<SLOUPEC PORADI="1">130842000001</SLOUPEC>	<SLOUPEC PORADI="2">USD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:00:06</SLOUPEC>	<SLOUPEC PORADI="8">205628510C100000</SLOUPEC>	<SLOUPEC PORADI="10">6402180807</SLOUPEC>	<SLOUPEC PORADI="11">6402180807</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-GBPUSD</SLOUPEC>	<SLOUPEC PORADI="14">S</SLOUPEC>	<SLOUPEC PORADI="18">0.20000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="2">																	
	<SLOUPEC PORADI="1">130842000002</SLOUPEC>	<SLOUPEC PORADI="2">CHF</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:00:10</SLOUPEC>	<SLOUPEC PORADI="8">205639330O100000</SLOUPEC>	<SLOUPEC PORADI="10">8005298180</SLOUPEC>	<SLOUPEC PORADI="11">8005298180</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-USDCHF</SLOUPEC>	<SLOUPEC PORADI="14">S</SLOUPEC>	<SLOUPEC PORADI="18">0.10000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="3">																	
	<SLOUPEC PORADI="1">130842000003</SLOUPEC>	<SLOUPEC PORADI="2">USD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:00:37</SLOUPEC>	<SLOUPEC PORADI="8">169356100O300000</SLOUPEC>	<SLOUPEC PORADI="10">7312190138</SLOUPEC>	<SLOUPEC PORADI="11">7312190138</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-EURUSD</SLOUPEC>	<SLOUPEC PORADI="14">B</SLOUPEC>	<SLOUPEC PORADI="18">0.30000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="4">																	
	<SLOUPEC PORADI="1">130842000004</SLOUPEC>	<SLOUPEC PORADI="2">USD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:01:19</SLOUPEC>	<SLOUPEC PORADI="8">205631930C100000</SLOUPEC>	<SLOUPEC PORADI="10">8507193112</SLOUPEC>	<SLOUPEC PORADI="11">8507193112</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-EURUSD</SLOUPEC>	<SLOUPEC PORADI="14">B</SLOUPEC>	<SLOUPEC PORADI="18">0.10000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="5">																	
	<SLOUPEC PORADI="1">130842000005</SLOUPEC>	<SLOUPEC PORADI="2">USD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:02:04</SLOUPEC>	<SLOUPEC PORADI="8">169338500C300000</SLOUPEC>	<SLOUPEC PORADI="10">8156254601</SLOUPEC>	<SLOUPEC PORADI="11">8156254601</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-EURUSD..</SLOUPEC>	<SLOUPEC PORADI="14">S</SLOUPEC>	<SLOUPEC PORADI="18">0.20000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="6">																	
	<SLOUPEC PORADI="1">130842000006</SLOUPEC>	<SLOUPEC PORADI="2">USD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:02:07</SLOUPEC>	<SLOUPEC PORADI="8">169353700C300000</SLOUPEC>	<SLOUPEC PORADI="10">8156254601</SLOUPEC>	<SLOUPEC PORADI="11">8156254601</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-AUDUSD..</SLOUPEC>	<SLOUPEC PORADI="14">S</SLOUPEC>	<SLOUPEC PORADI="18">0.20000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="7">																	
	<SLOUPEC PORADI="1">130842000007</SLOUPEC>	<SLOUPEC PORADI="2">USD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:02:15</SLOUPEC>	<SLOUPEC PORADI="8">205639430O100000</SLOUPEC>	<SLOUPEC PORADI="10">7409200458</SLOUPEC>	<SLOUPEC PORADI="11">7409200458</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-EURUSD</SLOUPEC>	<SLOUPEC PORADI="14">B</SLOUPEC>	<SLOUPEC PORADI="18">0.40000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="8">																	
	<SLOUPEC PORADI="1">130842000008</SLOUPEC>	<SLOUPEC PORADI="2">AUD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:02:27</SLOUPEC>	<SLOUPEC PORADI="8">169343800C300000</SLOUPEC>	<SLOUPEC PORADI="10">7801214773</SLOUPEC>	<SLOUPEC PORADI="11">7801214773</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-EURAUD..</SLOUPEC>	<SLOUPEC PORADI="14">B</SLOUPEC>	<SLOUPEC PORADI="18">1.00000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="9">																	
	<SLOUPEC PORADI="1">130842000009</SLOUPEC>	<SLOUPEC PORADI="2">USD</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:03:01</SLOUPEC>	<SLOUPEC PORADI="8">169357700O300000</SLOUPEC>	<SLOUPEC PORADI="10">7312190138</SLOUPEC>	<SLOUPEC PORADI="11">7312190138</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-EURUSD</SLOUPEC>	<SLOUPEC PORADI="14">B</SLOUPEC>	<SLOUPEC PORADI="18">0.20000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
<RADEK PORADI="10">																	
	<SLOUPEC PORADI="1">130842000010</SLOUPEC>	<SLOUPEC PORADI="2">JPY</SLOUPEC>	<SLOUPEC PORADI="3">04</SLOUPEC>	<SLOUPEC PORADI="4">04</SLOUPEC>	<SLOUPEC PORADI="5">I</SLOUPEC>	<SLOUPEC PORADI="6">2013-08-01</SLOUPEC>	<SLOUPEC PORADI="7">00:05:15</SLOUPEC>	<SLOUPEC PORADI="8">169359200O300000</SLOUPEC>	<SLOUPEC PORADI="10">7708232455</SLOUPEC>	<SLOUPEC PORADI="11">7708232455</SLOUPEC>	<SLOUPEC PORADI="13">TRBDCZP1XXX-EURJPY</SLOUPEC>	<SLOUPEC PORADI="14">S</SLOUPEC>	<SLOUPEC PORADI="18">0.15000</SLOUPEC>	<SLOUPEC PORADI="19">K</SLOUPEC>	<SLOUPEC PORADI="33">N</SLOUPEC>	<SLOUPEC PORADI="34">N</SLOUPEC>	<SLOUPEC PORADI="39">DIRECT</SLOUPEC>
</RADEK>																	
		</DATOVA-OBLAST>
	</DATA>
</VYDANI>
